id: P045ECBAC
initial_creation_type: ocr
source_metadata:
  volumes:
    5c8a659a1b0a44d793f377daf08f32e5:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: སློབ་དཔོན་ཀཱ་མ་ལ་ཤཱི་ལའི་སྨོན་ལམ་མུ་གཉིས་མ།
      total_pages: 1880
      volume_number: 116
